version: '3.8'

services:
  db:
    container_name: void_forms_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./sql:/sql
      - ./scripts:/scripts